
import = ["~/.config/alacritty/gruvbox_dark.toml"]
[window]
opacity = 0.70 
dynamic_title = false
padding = {x = 0, y = 0}
[shell]
program = "/bin/zsh"
[font.normal]
family = "JetBrainsMono Nerd Font"
style = "Regular"

[font.bold]
family = "JetBrainsMono Nerd Font"
style = "Bold"

[font.italic]
family = "JetBrainsMono Nerd Font"
style = "Italic"

[font.bold_italic]
family = "JetBrainsMono Nerd Font"
style = "Bold Italic"

[font]
size = 14 
[keyboard]
bindings = [
{mode = "AppCursor", key = "C", mods = "Control", action = "CopySelection"},
{mode = "AppCursor", key = "V", mods = "Control", action = "PasteSelection"}
]
[cursor.style]
blinking = "Never"

