import = ["~/.config/alacritty/gruvbox_dark.toml"]

[env]
WINIT_X11_SCALE_FACTOR = "0.9"

[window]
opacity = 1.00 
dynamic_title = false

[shell]
program = "/bin/zsh"

[font]
size = 14 
[font.normal]
family = "JetBrainsMono Nerd Font"
style = "Regular"

[font.bold]
family = "JetBrainsMono Nerd Font"
style = "Bold"

[font.italic]
family = "JetBrainsMono Nerd Font"
style = "Italic"

[font.bold_italic]
family = "JetBrainsMono Nerd Font"
style = "Bold Italic"

[cursor]
style = { blinking = "Never",shape = "Beam"}
vi_mode_style = { blinking = "Never", shape = "Block"}
