import = ["~/.config/alacritty/gruvbox_dark.toml"]
[window]
opacity = 0.70 
dynamic_title = false
padding = {x = 0, y = 0}

[env]
WINIT_X11_SCALE_FACTOR = "1.0"

[shell]
program = "/bin/zsh"

[font.normal]
family = "JetBrainsMono Nerd Font"
style = "Regular"

[font.bold]
family = "JetBrainsMono Nerd Font"
style = "Bold"

[font.italic]
family = "JetBrainsMono Nerd Font"
style = "Italic"

[font.bold_italic]
family = "JetBrainsMono Nerd Font"
style = "Bold Italic"

[font]
size = 14 

[cursor.style]
blinking = "Never"

